version: "3"
services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=todo-service
    volumes:
      - mongodb-data:/data/db

  todo-app:
    container_name: Todo
    build:
      context: ./todo
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_URI=mongodb://mongodb:27017/todo-service
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
      - mongodb

  notification-app:
    container_name: Notification
    build:
      context: ./notification
      dockerfile: Dockerfile
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka

  react-app:
    container_name: ReactApp
    build:
      context: ./todo-client
      dockerfile: Dockerfile
    environment:
      - TODO_BASE_URL=http://todo-app:3000
    ports:
      - "5173:5173"
    expose:
      - "5173"
    depends_on:
      - todo-app
    restart: unless-stopped
volumes:
  mongodb-data:
